### PR TITLE
Compile on Nightly

### PR DESCRIPTION
**Pull request by nixpulvis**
Get this crate working on nightly Rust again.

### To Do

- [ ] Fix the one failing test, by fixing `Helpers::sentence_case` and `Helpers::lowercase`.

### CODE REVIEW

**Comment by tikotzky** [comment]
Hi @nixpulvis,

Thanks for this PR!

As you noticed this project has been a little dormant :cry: 
I keep meaning to get back into and update it but unfortunately time is working against me.

With that being said if you're open to it I would love to give you collab access so you can get the project running again on stable.

Lemme know and I'll get you added :smile:

**Comment by nixpulvis** [comment]
Sure thing. My current plans are to get things working on stable and nightly (mostly done) then abstract some of the code with a few traits, possibly changing the interface a tiny bit. And work on a way to avoid allocations.

**Comment by tikotzky** [comment]
Sound great!

I added you as collab...

feel free to make things awesome :smiley:

**Comment by nixpulvis** [comment]
Should I still work through PRs waiting on your input?

**Comment by tikotzky** [comment]
I think working on PRs is nice since it allows everyone to follow along.

I'm ok with you merging your work once its complete, but I'll wait for @sethpollack to chime in since he did a lot of work on this as well.

**Comment by sethpollack** [comment]
Yeah PR is good. I haven't touched Rust for a while (I'm a little rusty), but if you want to collab with me I would love to add localization to this project.

**Comment by nixpulvis** [comment]
I'm working on some generalizations now. I'll push soon(ish)

**Comment by tikotzky** [comment]
:+1: :+1: :+1:

**Comment by nixpulvis** [comment]
Do I have permissions to push to crates.io?

**Comment by tikotzky** [comment]
adding you now...

**Comment by tikotzky** [comment]
done. lemme know if you have issues pushing to crates.io

**Comment by nixpulvis** [comment]
Done :tada:

**Comment by tikotzky** [comment]
awesome!

**Pull request merged**
